### ISSUE TITLE
move javascript validation to php

### ISSUE THREAD

**Issue by paulgibbs** [paulgibbs/buddypress-xcf#1]
I'm not going to include the validation in the JS files from the plugin (yet?) because I want to understand if there's something we can change in BuddyPress core to do it there.

**Comment by donmik** [comment]
In this commit https://github.com/paulgibbs/buddypress-xcf/commit/9660f2fd268a052de0b0b843b4521c28d411795e, I've changed my code to use buddypress "is_valid" method to validate the values of checkbox acceptance. I was using hidden fields and javascript but now it's not necessary.

**Comment by paulgibbs** [comment]
👍

FYI I am going to test and look through everything tomorrow, I've set out some time for it
